function [X, I, direction, avg_value]= X_calcu_full_model(x_mouse,y_mouse,action_probability,state_value,policy)
if x_mouse==1 && y_mouse==1
    tmp= [policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)];
    
    I= nex_step_func([policy{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        NaN,NaN,policy{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)]);
    direction= [1,4];
    avg_value= (state_value(16-(y_mouse+1),x_mouse)+state_value(16-(y_mouse),x_mouse+1))/2;
    
elseif x_mouse==1 && y_mouse==15
    tmp= [policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)];
    
    I= nex_step_func([NaN,policy{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        NaN,policy{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)]);
    direction= [2,4];
    avg_value= (state_value(16-(y_mouse-1),x_mouse)+state_value(16-(y_mouse),x_mouse+1))/2;
    
    
elseif x_mouse==15 && y_mouse==15
    tmp= [policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1)];
    
    I= nex_step_func([NaN,policy{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),NaN]);
    direction= [2,3];
    avg_value= (state_value(16-(y_mouse-1),x_mouse)+state_value(16-(y_mouse),x_mouse-1))/2;
    
    
elseif x_mouse==15 && y_mouse==1
    tmp= [policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1)];
    
    I= nex_step_func([policy{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        NaN,policy{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),NaN]);
    direction= [1,3];
    avg_value= (state_value(16-(y_mouse+1),x_mouse)+state_value(16-(y_mouse),x_mouse-1))/2;
    
    
elseif y_mouse==1
    tmp= [policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)];
    
    
    I= nex_step_func([policy{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        NaN,policy{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)]);
    direction= [1,3,4];
    avg_value= (state_value(16-(y_mouse+1),x_mouse)+state_value(16-(y_mouse),x_mouse-1)+state_value(16-(y_mouse),x_mouse+1))/3;
    
    
elseif y_mouse==15
    tmp= [policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)];
    
    I= nex_step_func([NaN,policy{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)]);
    direction= [2,3,4];
    avg_value= (state_value(16-(y_mouse-1),x_mouse)+state_value(16-(y_mouse),x_mouse+1)+state_value(16-(y_mouse),x_mouse-1))/3;
    
    
elseif x_mouse==15
    tmp= [policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1)];
    
    
    I= nex_step_func([policy{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),NaN]);
    direction= [1,2,3];
    avg_value= (state_value(16-(y_mouse+1),x_mouse)+state_value(16-(y_mouse-1),x_mouse)+state_value(16-(y_mouse),x_mouse-1))/3;
    
elseif x_mouse==1
    tmp= [policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)];
    
    I= nex_step_func([policy{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        NaN,policy{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)]);
    direction= [1,2,4];
    avg_value= (state_value(16-(y_mouse+1),x_mouse)+state_value(16-(y_mouse-1),x_mouse)+state_value(16-(y_mouse),x_mouse+1))/3;
    
    
else
    tmp= [policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(1)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(2)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(3)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(4)*action_probability{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)];
    
    
    I= nex_step_func([policy{16-y_mouse,x_mouse}(1)*state_value(16-(y_mouse+1),x_mouse),...
        policy{16-y_mouse,x_mouse}(2)*state_value(16-(y_mouse-1),x_mouse),...
        policy{16-y_mouse,x_mouse}(3)*state_value(16-(y_mouse),x_mouse-1),...
        policy{16-y_mouse,x_mouse}(4)*state_value(16-(y_mouse),x_mouse+1)]);
    direction= [1,2,3,4];
    avg_value= (state_value(16-(y_mouse+1),x_mouse)+state_value(16-(y_mouse-1),x_mouse)+state_value(16-(y_mouse),x_mouse+1)+...
        state_value(16-(y_mouse),x_mouse-1))/4;
    
end
X= sum(tmp);
end